### ISSUE TITLE
SingularException on sfmodel_fit

### ISSUE THREAD

**Issue by subes** [HungJenWang1991/SFrontiers.jl#4]
Hi,

thanks a lot for this great library.

I tried it with some made up values:
```
using Pkg;
isinstalled(pkg::String) = any(x -> x.name == pkg && x.is_direct_dep, values(Pkg.dependencies()));
if !isinstalled("DataFrames")
  Pkg.add("DataFrames")
end
using DataFrames;
if !isinstalled("SFrontiers")
  Pkg.add("SFrontiers")
end
using SFrontiers;

# input
y = [1,2,3]
x = [1.1 1.2 1.3;2.1 2.2 2.3;3.1 3.2 3.3]
cons = [1,1,1]

# run
sfmodel_spec(sftype(prod), sfdist(half), depvar(y), frontier(x), sigma_u_2(cons), sigma_v_2(cons))
res = sfmodel_fit()

# output between 0 and 1 as efficiency score (Battese and Coelli (1988) efficiency index)
res.bc
```

Why does this result in:
```
julia> res = sfmodel_fit()

###------------------------------------###
###  Estimating SF models using Julia  ###
###------------------------------------###

*********************************
       Model Specification:
*********************************
Model type: normal and half-normal

* In the case of type(cost), "- uᵢ" below is changed to "+ uᵢ".

depvar = frontier([:frontier_var1, :frontier_var2, :frontier_var3]) + vᵢ - uᵢ,

where vᵢ ∼ N(0, σᵥ²),
           σᵥ² = exp(log_σᵥ²) 
               = exp([:σᵥ²_var1]);
      uᵢ ∼ N⁺(0, σᵤ²),
           σᵤ² = exp(log_σᵤ²) 
               = exp([:σᵤ²_var1]);

ERROR: LinearAlgebra.SingularException(3)
Stacktrace:
 [1] checknonsingular
   @ /opt/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/factorization.jl:19 [inlined]
 [2] checknonsingular
   @ /opt/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/factorization.jl:21 [inlined]
 [3] #lu!#146
   @ /opt/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/lu.jl:82 [inlined]
 [4] #lu#153
   @ /opt/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/lu.jl:279 [inlined]
 [5] lu (repeats 2 times)
   @ /opt/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/lu.jl:278 [inlined]
 [6] \(A::Matrix{Float64}, B::Matrix{Float64})
   @ LinearAlgebra /opt/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:1142
 [7] sfmodel_fit(sfdat::DataFrame)
   @ SFrontiers ~/.julia/packages/SFrontiers/z3c87/src/SFmainfun.jl:523
 [8] sfmodel_fit()
   @ SFrontiers ~/.julia/packages/SFrontiers/z3c87/src/SFmainfun.jl:463
 [9] top-level scope
   @ REPL[12]:1
```

I would expect that I would just get a bad efficiency result or some intermediate result because it might not converge completely.

**Comment by subes** [comment]
These inputs work and converge:
```
y = [1,2,3,4,5,6,7,8,9,10]
x = [1.1 1.2 1.3;2.1 2.2 2.3;1.2 1.5 1.6;1.7 1.4 5.6;1.5 5.7 2.6;5.7 3.6 5.1;5.4 6.1 7.4;3.6 3.6 3.5;7.8 4.6 3.1;5.1 3.2 6.3]
cons = [1,1,1,1,1,1,1,1,1,1]
```
While these inputs fail because of a different reason:
```
julia> res = sfmodel_fit()

###------------------------------------###
###  Estimating SF models using Julia  ###
###------------------------------------###

*********************************
       Model Specification:
*********************************
Model type: normal and half-normal

* In the case of type(cost), "- uᵢ" below is changed to "+ uᵢ".

depvar = frontier([:frontier_var1, :frontier_var2, :frontier_var3]) + vᵢ - uᵢ,

where vᵢ ∼ N(0, σᵥ²),
           σᵥ² = exp(log_σᵥ²) 
               = exp([:σᵥ²_var1]);
      uᵢ ∼ N⁺(0, σᵤ²),
           σᵤ² = exp(log_σᵤ²) 
               = exp([:σᵤ²_var1]);

The warmstart run...


 * Status: failure (reached maximum number of iterations)

 * Candidate solution
    Final objective value:     2.283737e+00

 * Found with
    Algorithm:     Nelder-Mead

 * Convergence measures
    √(Σ(yᵢ-ȳ)²)/n ≰ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    100
    f(x) calls:    178
 
The warmstart results are:
[-7.519202576500893, 12.308079335686989, -3.8299004614481365, -0.18610923543137942, -4.495971300254554]


Starting the optimization run...


 * Status: success

 * Candidate solution
    Final objective value:     -3.040991e+02

 * Found with
    Algorithm:     Newton's Method

 * Convergence measures
    |x - x'|               = 0.00e+00 ≤ 0.0e+00
    |x - x'|/|x'|          = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = 8.30e+13 ≰ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    59
    f(x) calls:    859
    ∇f(x) calls:   681
    ∇²f(x) calls:  59
 
The resulting coefficient vector is:
[-1.6391774941165027, 6.278354988232893, -3.639177494116389, -62.123744495933714, -63.4693349323398]

Note that the estimation may not have converged properly. The gradients are problematic (too large, > 0.1, or others).

Some of the diagonal elements of the var-cov matrix are non-positive, indicating problems in the convergence. The estimation is abort.

ERROR: DomainError with -6.491724028538927e-30:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
  [1] throw_complex_domainerror(f::Symbol, x::Float64)
    @ Base.Math ./math.jl:33
  [2] sqrt
    @ ./math.jl:567 [inlined]
  [3] _broadcast_getindex_evalf
    @ ./broadcast.jl:670 [inlined]
  [4] _broadcast_getindex
    @ ./broadcast.jl:643 [inlined]
  [5] getindex
    @ ./broadcast.jl:597 [inlined]
  [6] macro expansion
    @ ./broadcast.jl:961 [inlined]
  [7] macro expansion
    @ ./simdloop.jl:77 [inlined]
  [8] copyto!
    @ ./broadcast.jl:960 [inlined]
  [9] copyto!
    @ ./broadcast.jl:913 [inlined]
 [10] copy
    @ ./broadcast.jl:885 [inlined]
 [11] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(sqrt), Tuple{Vector{Float64}}})
    @ Base.Broadcast ./broadcast.jl:860
 [12] sfmodel_fit(sfdat::DataFrame)
    @ SFrontiers ~/.julia/packages/SFrontiers/z3c87/src/SFmainfun.jl:718
 [13] sfmodel_fit()
    @ SFrontiers ~/.julia/packages/SFrontiers/z3c87/src/SFmainfun.jl:463
 [14] top-level scope
    @ REPL[40]:1
```

For this case it might be good to have a parameter to tell that the result should still be generated even if the result did not converge completely (just use the best effort result).

**Comment by HungJenWang1991** [comment]
Hi,

Why does this result in:

julia> sfmodel_spec(sftype(prod), sfdist(trun), depvar(y),
frontier(x), sigma_u_2(cons), sigma_v_2(cons))

ERROR: "For the truncated-normal model, the μ equation is missing in
sfmodel_spec()."

=> Because you had `sfdist(trun)` in this line, which indicates a
truncated-normal distribution for the inefficiency term. For this
distribution, you need to specify the `mu()` equation.

You may want to change it to `sfdist(half)` and try again. On the other
hand, your `x` input looks like the data is collinear to each other. You
should try other figures. Then again, numerical optimization on a
highly-nonlinear model with a mere 3 data points may not be successful
(will encounter numerical issues). I suggest you use one of the datasets I
provided on the SFrontiers.jl web page to try out the program.

Hope it helps.

Hung-Jen







Edwin Stang ***@***.***> 於 2021年12月26日 週日 下午9:52寫道：

**Comment by HungJenWang1991** [comment]
I hope my previous email has addressed the issue. It's a data problem. I
probably should do a better job catching the DomainError problem.

Hung-Jen

Edwin Stang ***@***.***> 於 2021年12月26日 週日 下午10:04寫道：

**Comment by subes** [comment]
Please re-read the first error message (here on github and not in your mailbox). I copied the wrong results and already used "half" as the result: `ERROR: LinearAlgebra.SingularException(3)`

I am planning to use SFrontiers to rank stocks by efficiency. Ideally the algorithm should also work for only a few candidates and tell which one has a higher rank than the others.

**Comment by HungJenWang1991** [comment]
Sorry for missing that.

Regarding the first error message: The input of x = [1.1 1.2 1.3;2.1 2.2
2.3;3.1 3.2 3.3] results in perfect collinearity between the three columns
and having all of them as independent variables would fail any model. The
error message occurs at the place where an OLS is used to get coefficients
as initial values, and because of the perfect collinearity the OLS fails
(the matrix is singular and cannot be inverted).

Edwin Stang ***@***.***> 於 2021年12月26日 週日 下午11:23寫道：

**Comment by subes** [comment]
Ah ok, that makes sense. I guess I will just fallback to a wrong response when the model can not be calculated. But I expect not all inputs that will be created by the process to converge or run error free. Thus corner cases will need to be handled (at least by myself).

**Comment by subes** [comment]
Though if there is a setting to be more lenient with none-convergence that would be good as well. E.g. when the calculation did not converge after the max iterations, don't abort but instead output the best effort result.

**Comment by HungJenWang1991** [comment]
That's actually the current behavior. That is, if the optimization process
hits the iteration limit, it would --provided there are no numerical
issues-- print results from the last iteration with a warning that the
convergence is false. To verify that this is indeed the case, you may set a
low iteration limit using something like `sfmodel_opt(main_maxIT(2))`. Note
you could use a lower convergence criterion as well by the `tolerance()`
option in `sfmodel_opt()`.



Edwin Stang ***@***.***> 於 2021年12月26日 週日 下午11:57寫道：

**Comment by subes** [comment]
Thanks for the info. I guess we can thus close this issue.
